apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-ex-db-dev
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://gitea-gitea.apps.ocp4.sandbox520.opentlc.com/giteaadmin/cluster-gitops.git'
    targetRevision: HEAD
    path: applications/django-ex-db
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-ex-dev
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://gitea-gitea.apps.ocp4.sandbox520.opentlc.com/giteaadmin/cluster-gitops.git'
    targetRevision: HEAD
    path: applications/django-ex
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
