apiVersion: v1
kind: Secret
metadata:
  name: gitea-runner-secret
  namespace: {{ .Values.namespace | default "gitea" }}
type: Opaque
stringData:
  token: {{ .Values.gitea.registrationToken | quote }}
